### ISSUE TITLE
ns出错了，签到不了了

### ISSUE THREAD

**Issue by falcon9709** [YYWO/NodeSeek-Signin#3]
Run python nodeseek_sign.py
/opt/hostedtoolcache/Python/3.[11](https://github.com/falcon9709/NodeSeek-Sign/actions/runs/9161834603/job/25212598354#step:5:12).8/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.nodeseek.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
发生异常: Expecting value: line 1 column 1 (char 0)

**Comment by YYWO** [comment]
触发了Cloudflare拦截验证

**Comment by YYWO** [comment]
简单来说就是IP问题，脚本丢到本地定时运行就能跑了，定时运行推荐你使用青龙面板或者服务器的crontab
