### ISSUE TITLE
建议环境变量名称适配青龙

### ISSUE THREAD

**Issue by Blink1024** [YYWO/NodeSeek-Signin#4]
有个定时任务管理平台项目-青龙
[https://github.com/whyour/qinglong](https://github.com/whyour/qinglong)
配置文件给了一些常用的环境变量名称
[https://github.com/whyour/qinglong/blob/develop/sample/config.sample.sh](https://github.com/whyour/qinglong/blob/develop/sample/config.sample.sh)
建议适配一下,用青龙的话就不用修改脚本或者新建环境变量,直接拉取就能用
例如修改为
|  名称  |                 含义                  |
| :----: | :-----------------------------------: |
| NS_COOKIE | 论坛用户cookie，自行在浏览器F12中查看 |
| PUSH_PLUS_TOKEN| pushplus中的用户token，用于推送，非必需 |
| TG_BOT_TOKEN | 通过电报 BotFather 创建的机器人Token，非必需 |
| TG_USER_ID | 电报 getuseridbot 中获取到的纯数字ID，非必需 |
| TG_API_HOST | Telegram api自建反向代理地址，非必需 |

**Comment by YYWO** [comment]
已更新，变量参考青龙面板的config.sh，其余的不变
